[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "doti18n"
version = "0.3.1"
description = "Python library for loading YAML localizations with dot access and pluralization."
long_description = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = "MIT"
authors = [
    {name = "darkj3suss", email = "asdzxco@protonmail.com"}
]
keywords = ["localization", "i18n", "l10n", "translate", "yaml", "json", "yml", "text processing", "dot access", "pluralization", "babel"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Localization",
    "Topic :: Text Processing :: Linguistic",
]

[project.dependencies]
babel = "^2.17.0"

[project.optional-dependencies]
yaml = [
    "PyYAML>=6.0"
]


[tool.ruff]
line-length = 120
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]


[tool.ruff.lint]
select = ["E", "W", "F", "I", "C90", "N", "D"]
ignore = ["D203", "D211", "D104", "D212", "D100"]

[tool.ruff.lint.isort]
known-first-party = ["doti18n"]


[tool.black]
line-length = 120
target-version = ['py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
exclude = ["venv", "tests/"]


[project.urls]
Homepage = "https://github.com/darkj3suss/doti18n"
BugTracker = "https://github.com/darkj3suss/doti18n/issues"
Repository = "https://github.com/darkj3suss/doti18n"

